package com.aplikasi.bean;
// Generated Nov 10, 2016 9:58:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private String nama;
     private String alamat;
     private String jenkel;
     private String noHp;
     private String fakultas;
     private String jurusan;
     private BigDecimal ipk;

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim) {
        this.nim = nim;
    }
    public Mahasiswa(String nim, String nama, String alamat, String jenkel, String noHp, String fakultas, String jurusan, BigDecimal ipk) {
       this.nim = nim;
       this.nama = nama;
       this.alamat = alamat;
       this.jenkel = jenkel;
       this.noHp = noHp;
       this.fakultas = fakultas;
       this.jurusan = jurusan;
       this.ipk = ipk;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getJenkel() {
        return this.jenkel;
    }
    
    public void setJenkel(String jenkel) {
        this.jenkel = jenkel;
    }
    public String getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(String noHp) {
        this.noHp = noHp;
    }
    public String getFakultas() {
        return this.fakultas;
    }
    
    public void setFakultas(String fakultas) {
        this.fakultas = fakultas;
    }
    public String getJurusan() {
        return this.jurusan;
    }
    
    public void setJurusan(String jurusan) {
        this.jurusan = jurusan;
    }
    public BigDecimal getIpk() {
        return this.ipk;
    }
    
    public void setIpk(BigDecimal ipk) {
        this.ipk = ipk;
    }




}


